#pragma once



#define MSG_LOGIN					1
	#define LOGIN_AUTH						1
	#define LOGIN_LOGIN						2
	#define LOGIN_ACREATION					3
	#define LOGIN_CCHOOSE					4
	#define LOGIN_ACCINFO					5
	#define LOGIN_CCREATE					6
	#define LOGIN_CCREATED					7
	#define LOGIN_CHARCHOSEN				8


#define MSG_MESSAGE					120
	#define MESSAGE_ANAMETAKEN				1
	#define MESSAGE_EMAILREGISTERED			2
	#define MESSAGE_REGISTERED				3
	#define MESSAGE_INVALIDACCNAME			4
	#define MESSAGE_INVALIDPASS				5
	#define MESSAGE_SERVERFULL				6
	#define MESSAGE_INVALIDCHARNAME			7
	#define MESSAGE_CHARNAMETAKEN			8
	#define MESSAGE_FAILUNKOWN				9


#define MSG_USERINPUT				2
	#define USERINPUT_MOVEMENT				1


#define MSG_INFORMATION				3
	#define INFORMATION_COORDS				1
	#define INFORMATION_PLAYERINFO			2

	
#define MSG_CHATTING				4
	#define CHATTING_NEWMESSAGE				1
